
--INSERT INTO PC VALUES(12, 1100,2400,2048,500, '52x', 299)

--DELETE FROM PC WHERE MODEL =1100

--DELETE FROM LAPTOP WHERE MODEL IN (SELECT MODEL FROM PRODUCT WHERE MAKER NOT IN (SELECT MAKER FROM PRODUCT WHERE TYPE = 'Printer')) 

--UPDATE PRODUCT SET MAKER = 'A' WHERE MAKER = 'B'

--UPDATE PC SET PRICE /= 2,HD +=20

--UPDATE LAPTOP SET SCREEN +=1 WHERE MODEL IN (SELECT MODEL FROM PRODUCT WHERE MAKER = 'B')