CREATE TABLE AIRLINE(
CODE INT PRIMARY KEY,
NAME VARCHAR(30),
COUNTRY VARCHAR(30),
)

CREATE TABLE AIRPORT(
CODE INT PRIMARY KEY,
NAME VARCHAR(30),
COUNTRY VARCHAR(30),
CITY VARCHAR(30)
)

CREATE TABLE AIRPLANE(
CODE INT PRIMARY KEY,
TYPE CHAR,
SEATS INT,
YEAR INT
)

CREATE TABLE FLIGHT(
FNUMBER INT PRIMARY KEY,
AIRLINE_OPERATOR INT,
DEP_AIRPORT INT,
ARR_AIRPORT INT,
FLIGHT_TIME DATETIME,
FLIGHT_DURATION TIME,
AIRPLANE INT,
CONSTRAINT FK_AIRLINE  FOREIGN KEY(AIRLINE_OPERATOR) REFERENCES AIRLINE(CODE),
CONSTRAINT FK_DEP_AIRPORT FOREIGN KEY(DEP_AIRPORT) REFERENCES AIRPORT(CODE),
CONSTRAINT FK_ARR_AIRPORT FOREIGN KEY(ARR_AIRPORT) REFERENCES AIRPORT(CODE),
CONSTRAINT FK_AIRPLANE FOREIGN KEY(AIRPLANE) REFERENCES AIRPLANE(CODE)
)


CREATE TABLE CUSTOMER(
ID INT PRIMARY KEY,
NAME VARCHAR(30),
LNAME VARCHAR(30),
EMAIL VARCHAR(30)
)

CREATE TABLE AGENCY(
NAME VARCHAR(30) PRIMARY KEY,
COUNTRY VARCHAR(30),
CITY VARCHAR(30),
PHONE  VARCHAR(15)
)

CREATE TABLE BOOKING(
CODE INT PRIMARY KEY,
AGENCY VARCHAR(30),
AIRLINE_CODE INT,
FLIGHT_NUMBER INT,
CUSTOMER_ID INT,
BOOKING_DATE DATE, 
FLIGHT_DATE DATE,
PRICE DECIMAL(10,2),
STATUS BIT,
CONSTRAINT FK_AGENCY FOREIGN KEY(AGENCY) REFERENCES AGENCY(NAME),
CONSTRAINT FK_AIRLINE FOREIGN KEY(AIRLINE_CODE) REFERENCES AIRLINE(CODE),
CONSTRAINT FK_FNUMBER FOREIGN KEY(FLIGHT_NUMBER) REFERENCES FLIGHT(FNUMBER),
CONSTRAINT FK_CUSTOMER FOREIGN KEY(CUSTOMER_ID) REFERENCES CUSTOMER(ID)
)