SELECT SHIPS.NAME
FROM CLASSES, SHIPS
WHERE CLASSES.CLASS = SHIPS.CLASS AND CLASSES.DISPLACEMENT > 50000

SELECT SHIPS.NAME, CLASSES.DISPLACEMENT, CLASSES.NUMGUNS
FROM CLASSES, OUTCOMES, SHIPS
WHERE  OUTCOMES.BATTLE = 'Guadalcanal' AND
	   OUTCOMES.SHIP = SHIPS.NAME  AND
	   SHIPS.CLASS = CLASSES.CLASS


SELECT T1.COUNTRY
FROM CLASSES AS T1, CLASSES AS T2
WHERE T1.TYPE = 'bb' AND T2.TYPE = 'bc' AND
	  T1.COUNTRY = T2.COUNTRY


SELECT T1.SHIP
FROM OUTCOMES AS T1, OUTCOMES AS T2
WHERE T1.SHIP = T2.SHIP AND
	  T1.RESULT = 'damaged' AND
	  T1.BATTLE != T2.BATTLE
