SELECT TITLE, NAME
FROM MOVIE JOIN MOVIEEXEC
	 ON PRODUCERC#= CERT#
WHERE PRODUCERC# = (SELECT PRODUCERC# 
					FROM MOVIE 
					WHERE TITLE = 'Star wars')


SELECT DISTINCT NAME
FROM ((SELECT * 
	  FROM STARSIN 
	  WHERE STARNAME = 'Harrison Ford') AS T1 JOIN MOVIE
	  ON MOVIETITLE = TITLE) JOIN MOVIEEXEC 
								  ON CERT# = PRODUCERC#


SELECT DISTINCT STUDIONAME, STARNAME
FROM MOVIE JOIN STARSIN ON MOVIETITLE = TITLE
ORDER BY STUDIONAME


SELECT STARNAME, NETWORTH, TITLE
FROM (MOVIE JOIN STARSIN 
	 ON MOVIETITLE = TITLE) JOIN MOVIEEXEC 
	 ON CERT# = PRODUCERC#
WHERE NETWORTH >= ALL (SELECT NETWORTH FROM MOVIEEXEC)


SELECT NAME, MOVIETITLE
FROM MOVIESTAR FULL JOIN STARSIN ON STARNAME = NAME
WHERE  STARNAME IS NULL

