(SELECT MAKER, PRODUCT.MODEL, TYPE
FROM PRODUCT LEFT JOIN LAPTOP 
ON PRODUCT.MODEL = LAPTOP.MODEL
WHERE PRICE IS NULL)
INTERSECT
(SELECT MAKER, PRODUCT.MODEL, TYPE
FROM PRODUCT LEFT JOIN PC 
ON PRODUCT.MODEL = PC.MODEL
WHERE PRICE IS NULL)
INTERSECT
(SELECT MAKER, PRODUCT.MODEL, PRODUCT.TYPE
FROM PRODUCT LEFT JOIN PRINTER 
ON PRODUCT.MODEL = PRINTER.MODEL
WHERE PRICE IS NULL)


SELECT MAKER FROM product WHERE TYPE LIKE 'Laptop'
INTERSECT
SELECT MAKER FROM product WHERE TYPE LIKE 'Printer'


SELECT DISTINCT  T1.HD
FROM LAPTOP AS T1 JOIN LAPTOP AS T2 ON T1.HD = T2.HD
WHERE T1.CODE < T2.CODE


SELECT *
FROM PC LEFT JOIN PRODUCT ON PC.MODEL = PRODUCT.MODEL
WHERE MAKER IS NULL
