SELECT *
FROM SHIPS JOIN CLASSES ON SHIPS.CLASS = CLASSES.CLASS

SELECT *
FROM SHIPS RIGHT JOIN CLASSES ON SHIPS.CLASS = CLASSES.CLASS 
WHERE SHIPS.NAME IS NOT NULL OR CLASSES.CLASS IN (SELECT NAME FROM SHIPS)

SELECT COUNTRY, NAME
FROM(SELECT *
	 FROM SHIPS LEFT JOIN OUTCOMES ON NAME = SHIP
	 WHERE BATTLE IS NULL) AS T1 JOIN CLASSES ON  CLASSES.CLASS = T1.CLASS
ORDER BY COUNTRY


SELECT Ships.NAME AS 'Ship Name'
FROM SHIPS JOIN CLASSES ON SHIPS.CLASS = CLASSES.CLASS
WHERE LAUNCHED = 1916 AND NUMGUNS >= 7


SELECT ship, battle, date
FROM OUTCOMES JOIN BATTLES ON BATTLE = NAME
WHERE RESULT = 'sunk'
ORDER BY NAME


SELECT NAME, DISPLACEMENT, LAUNCHED
FROM SHIPS JOIN CLASSES ON SHIPS.CLASS = CLASSES.CLASS
WHERE SHIPS.NAME = CLASSES.CLASS


SELECT *
FROM CLASSES  LEFT JOIN SHIPS ON CLASSES.CLASS = SHIPS.CLASS
WHERE LAUNCHED IS NULL


SELECT NAME, DISPLACEMENT, NUMGUNS, RESULT
FROM (SELECT SHIP, RESULT FROM OUTCOMES WHERE BATTLE = 'North Atlantic')AS T1 
	  JOIN SHIPS 
	  ON T1.SHIP = SHIPS.NAME JOIN CLASSES ON CLASSES.CLASS = SHIPS.CLASS
