SELECT DISTINCT COUNTRY
FROM CLASSES
WHERE NUMGUNS >= ALL (SELECT NUMGUNS FROM CLASSES)


SELECT DISTINCT CLASS 
FROM SHIPS 
WHERE NAME IN (SELECT SHIP
			   FROM OUTCOMES 
			   WHERE RESULT = 'sunk')


SELECT NAME, CLASS
FROM SHIPS
WHERE CLASS IN (SELECT CLASS FROM CLASSES WHERE BORE = 16)


SELECT NAME
FROM BATTLES
WHERE NAME IN (SELECT BATTLE
			   FROM OUTCOMES 
			   WHERE SHIP IN (SELECT NAME
							  FROM SHIPS 
							  WHERE CLASS = 'Kongo'))


SELECT  SHIPS.CLASS, SHIPS.NAME
FROM SHIPS,CLASSES AS T1
WHERE SHIPS.CLASS = T1.CLASS AND T1.NUMGUNS >= ALL (SELECT NUMGUNS
													FROM CLASSES
													WHERE CLASSES.BORE = T1.BORE)
ORDER BY CLASS
