SELECT COUNT(CLASS)
FROM CLASSES
WHERE TYPE = 'bb'


SELECT CLASS, AVG(NUMGUNS)
FROM CLASSES
WHERE TYPE = 'bb'
GROUP BY CLASS


SELECT AVG(NUMGUNS)
FROM CLASSES


SELECT CLASSES.CLASS, MIN(LAUNCHED), MAX(LAUNCHED)
FROM CLASSES JOIN SHIPS ON CLASSES.CLASS = SHIPS.CLASS
GROUP BY CLASSES.CLASS

SELECT CLASSES.CLASS, COUNT(*)
FROM OUTCOMES JOIN SHIPS ON SHIP = NAME JOIN CLASSES ON CLASSES.CLASS = SHIPS.CLASS
WHERE RESULT = 'sunk'
GROUP BY CLASSES.CLASS


SELECT CLASS, COUNT(*)
FROM OUTCOMES JOIN SHIPS ON SHIP = NAME 
WHERE RESULT = 'sunk' AND CLASS IN (SELECT CLASS
											FROM SHIPS
											GROUP BY CLASS
											HAVING COUNT(*) >=2)
GROUP BY CLASS


SELECT COUNTRY, AVG(BORE)
FROM SHIPS JOIN CLASSES ON CLASSES.CLASS = SHIPS.CLASS
GROUP BY COUNTRY

