SELECT AVG(SPEED)
FROM PC


SELECT MAKER, AVG(SCREEN)
FROM LAPTOP JOIN PRODUCT ON LAPTOP.MODEL = PRODUCT.MODEL
GROUP BY MAKER


SELECT AVG(SPEED)
FROM  LAPTOP
WHERE PRICE > 1000


SELECT AVG(PRICE)
FROM PC JOIN PRODUCT ON PC.MODEL = PRODUCT.MODEL
GROUP BY MAKER
HAVING MAKER = 'A'


SELECT AVG(T1.PRICE)
FROM(SELECT PRICE
	 FROM PC JOIN PRODUCT ON PC.MODEL = PRODUCT.MODEL
	 WHERE MAKER = 'B'
	 UNION ALL
	 SELECT PRICE
	 FROM LAPTOP JOIN PRODUCT ON LAPTOP.MODEL = PRODUCT.MODEL
	 WHERE MAKER = 'B'
) AS T1


SELECT SPEED,AVG(PRICE)
FROM PC
GROUP BY SPEED


SELECT MAKER, COUNT(*)
FROM PRODUCT JOIN PC ON PC.MODEL = PRODUCT.MODEL
GROUP BY MAKER
HAVING COUNT(*) >= 3


SELECT MAKER, PRICE
FROM PRODUCT JOIN PC ON PC.MODEL = PRODUCT.MODEL
WHERE PRICE = (SELECT MAX(PRICE) FROM PC)


SELECT AVG(PRICE)
FROM PC
WHERE SPEED > 800





SELECT MAKER,AVG(HD)
FROM PC JOIN PRODUCT ON PC.MODEL=PRODUCT.MODEL
WHERE MAKER IN((SELECT MAKER
				FROM PRODUCT
				WHERE TYPE = 'PC')
				INTERSECT
			   (SELECT MAKER
				FROM PRODUCT
				WHERE TYPE = 'PRINTER'))
GROUP BY MAKER